apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.application.appName }}
  labels:
    name: {{ .Values.application.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.application.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.appName }}
    spec: 
      hostname: {{ .Values.application.appName }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: True
      containers:
        - name: {{ .Values.application.appName }}
          image: {{ .Values.application.image }}:{{ .Values.application.imageVersion }}
          {{- if .Values.configuration }}
          env:
            {{- if .Values.configuration.sshkey }}
            - name: VM_SSH_AUTHORIZED_KEY
              value: {{ .Values.configuration.sshkey }}
            {{- end }}
            {{- if .Values.configuration.debug }}
            - name: DEBUG
              value: {{ .Values.configuration.debug }}
            {{- end }}
            {{- if .Values.configuration.dry_run_only }}
            - name: DRY_RUN_ONLY
              value: {{ .Values.configuration.dry_run_only }}
            {{- end }}
            {{- if .Values.configuration.copy_image_backup }}
            - name: COPY_IMAGE_BACKUP
              value: {{ .Values.configuration.copy_image_backup }}
            {{- end }}
            {{- if .Values.configuration.default_image }}
            - name: DEFAULT_IMAGE
              value: {{ .Values.configuration.default_image }}
            {{- end }}
            {{- if .Values.configuration.default_kernel_version }}
            - name: DEFAULT_KERNEL_VERSION
              value: {{ .Values.configuration.default_kernel_version }}
            {{- end }}
            {{- if .Values.configuration.vm_username }}
            - name: VM_USERNAME
              value: {{ .Values.configuration.vm_username }}
            {{- end }}
            {{- if .Values.configuration.vm_password }}
            - name: VM_PASSWORD
              value: {{ .Values.configuration.vm_password }}
            {{- end }}
            {{- if .Values.configuration.vm_salt }}
            - name: VM_SALT
              value: {{ .Values.configuration.vm_salt }}
            {{- end }}
            {{- if .Values.configuration.password_encrypted }}
            - name: VM_PASSWORD_ENCRYPTED
              value: {{ .Values.configuration.password_encrypted }}
            {{- end }}
            {{- if .Values.configuration.vm_hostname }}
            - name: VM_HOSTNAME
              value: {{ .Values.configuration.vm_hostname }}
            {{- end }}
            {{- if .Values.configuration.kernel_version }}
            - name: KERNEL_VERSION
              value: {{ .Values.configuration.kernel_version }}
            {{- end }}
            {{- if .Values.configuration.default_dir_image }}
            - name: DEFAULT_DIR_IMAGE
              value: {{ .Values.configuration.default_dir_image }}
            {{- end }}
            {{- if .Values.configuration.default_dir_k3s_var_linux_root }}
            - name: DEFAULT_DIR_K3S_VAR_LINUX_ROOT
              value: {{ .Values.configuration.default_dir_k3s_var_linux_root }}
            {{- end }}
            {{- if .Values.configuration.default_source_image }}
            - name: DEFAULT_IMAGE_SOURCE_URL
              value: {{ .Values.configuration.default_source_image }}
            {{- end }}
            {{- if .Values.configuration.default_kvm_host_sshd_port }}
            - name: DEFAULT_KVM_HOST_SSHD_PORT
              value: {{ .Values.configuration.default_kvm_host_sshd_port }}
            {{- end }}
            {{- if .Values.configuration.default_kvm_host_containerd_port }}
            - name: DEFAULT_KVM_HOST_CONTAINERD_PORT
              value: {{ .Values.configuration.default_kvm_host_containerd_port }}
            {{- end }}
            {{- if .Values.configuration.default_csi_grpc_proxy_url }}
            - name: DEFAULT_CSI_GRPC_PROXY_URL
              value: {{ .Values.configuration.default_csi_grpc_proxy_url }}
            {{- end }}
            {{- if .Values.configuration.default_kvm_ports_redirect }}
            - name: DEFAULT_KVM_PORTS_REDIRECT
              value: {{ .Values.configuration.default_kvm_ports_redirect }}
            {{- end }}
            {{- if .Values.configuration.kvm_cpu }}
            - name: KVM_CPU
              value: {{ .Values.configuration.kvm_cpu }}
            {{- end }}
            {{- if .Values.configuration.kvm_memory }}
            - name: KVM_MEMORY
              value: {{ .Values.configuration.kvm_memory }}
            {{- end }}
            {{- if .Values.configuration.run_bare_kernel }}
            - name: RUN_BARE_KERNEL
              value: {{ .Values.configuration.run_bare_kernel }}
            {{- end }}
            {{- if .Values.configuration.rimd_articaft_url }}
            - name: DEFAULT_RIMD_ARTIFACT_URL
              value: {{ .Values.configuration.rimd_articaft_url }}
            {{- end }}
            {{- if .Values.configuration.rimd_atifact_url_user }}
            - name: RIMD_ARTIFACT_URL_USER
              valueFrom:
                secretKeyRef:
                  name: rimd-access-credentials
                  key: user
              value: {{ .Values.configuration.rimd_atifact_url_user }}
            {{- end }}
            {{- if .Values.configuration.rimd_atifact_url_pass }}
            - name: RIMD_ARTIFACT_URL_PASS
              valueFrom:
                secretKeyRef:
                  name: rimd-access-credentials
                  key: pass
              value: {{ .Values.configuration.rimd_atifact_url_pass }}
            {{- end }}
            {{- if .Values.configuration.rimd_artifact_url_token }}
            - name: RIMD_ARTIFACT_URL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rimd-access-credentials
                  key: token
              value: {{ .Values.configuration.rimd_artifact_url_token }}
            {{- end }}
            {{- if .Values.configuration.rimd_artifact_filename }}
            - name: DEFAULT_RIMD_ARTIFACT_FILENAME
              value: {{ .Values.configuration.rimd_artifact_filename }}
            {{- end }}
            {{- if .Values.configuration.rimd_kernel_filename }}
            - name: DEFAULT_RIMD_KERNEL_FILENAME
              value: {{ .Values.configuration.rimd_kernel_filename }}
            {{- end }}
            {{- if .Values.configuration.rimd_image_filename }}
            - name: DEFAULT_RIMD_IMAGE_FILENAME
              value: {{ .Values.configuration.rimd_image_filename }}
            {{- end }}
            {{- if .Values.configuration.rimd_filesystem_filename }}
            - name: DEFAULT_RIMD_FILESYSTEM_FILENAME
              value: {{ .Values.configuration.rimd_filesystem_filename }}
            {{- end }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            {{- if .Values.configuration.local_node_image_dir }}
            - name: image
              mountPath: /root/image
            {{- end }}
            - name: kubelet
              mountPath: /var/lib/kubelet
            - name: pods
              mountPath: /var/log/pods
      volumes:
        {{- if .Values.configuration.local_node_image_dir }}
        - name: image
          hostPath:
            path: {{ .Values.configuration.local_node_image_dir }}
        {{- end }}
        - name: kubelet
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: pods
          hostPath:
            path: /var/log/pods
            type: Directory
      terminationGracePeriodSeconds: 30
{{- if or .Values.configuration.rimd_atifact_url_user .Values.configuration.rimd_atifact_url_pass .Values.configuration.rimd_artifact_url_token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rimd-access-credentials
data:
  {{- if .Values.configuration.rimd_atifact_url_user }}
  user: {{ .Values.configuration.rimd_atifact_url_user }}
  {{- end }}
  {{- if.Values.configuration.rimd_atifact_url_pass }}
  pass: {{ .Values.configuration.rimd_atifact_url_pass }}
  {{- end }}
  {{- if.Values.configuration.rimd_artifact_url_token }}
  token: {{ .Values.configuration.rimd_artifact_url_token }}
  {{- end }}
{{- end }}
