unset ADDITIONAL_9P_MOUNTS
unset DEFAULT_DIR_IMAGE
unset DISABLE_CONTAINERD_CSI_PROXY
unset DISABLE_9P_KUBELET_MOUNTS
unset DEFAULT_KVM_PORTS_REDIRECT
unset DEBUG DRY_RUN_ONLY
unset RUN_BARE_KERNEL
unset ENABLE_VIRTIO_GPU
unset DEFAULT_VIRTIO_GPU_VRAM
unset ALWAYS_REUSE_DISK_IMAGE 

export VM_HOSTNAME=hydra-isolated
export DEFAULT_DIR_IMAGE=$(pwd)/image-hydra-isolated
export EXTERNAL_9P_KUBELET_MOUNTS=1
export COPY_IMAGE_BACKUP=0
export DEFAULT_KVM_DISK_SIZE=10
export DEFAULT_KVM_HOST_SSHD_PORT=5556

./start-vm.sh
