#!/bin/bash

: ${VM_HOSTNAME:="hydra-isolated-krun"}
: ${DEFAULT_DIR_IMAGE:="$(pwd)/image-hydra-isolated-krun"}
: ${EXTERNAL_9P_KUBELET_MOUNTS:=1}
: ${DISABLE_9P_KUBELET_MOUNTS:=0}
: ${COPY_IMAGE_BACKUP:=1}
: ${DEFAULT_KVM_DISK_SIZE:=16}
: ${DEFAULT_KVM_HOST_SSHD_PORT:=5557}
: ${DEFAULT_KVM_PORTS_REDIRECT:="30800:8000;30801:8001;30802:8002"}
: ${DEFAULT_KVM_DARWIN_CPU:=4}
: ${DEFAULT_IMAGE:="debian-13-generic-arm64-20250814-2204.qcow2"}
: ${DEFAULT_KERNEL_VERSION:=""}
: ${DEFAULT_IMAGE_SOURCE_URL:="https://cloud.debian.org/images/cloud/trixie/20250814-2204"}
#: ${INSTALL_ADDITIONAL_DEBS:="http://http.us.debian.org/debian/pool/main/l/linux/linux-image-6.16-arm64-unsigned_6.16.1-1~exp1_arm64.deb"}
: ${ENABLE_REBOOT_AFTER_INSTALLATION:=1}
: ${COPY_IMAGE_BACKUP:=1}

export VM_HOSTNAME
export DEFAULT_DIR_IMAGE
export EXTERNAL_9P_KUBELET_MOUNTS
export DISABLE_9P_KUBELET_MOUNTS
export COPY_IMAGE_BACKUP
export DEFAULT_KVM_DISK_SIZE
export DEFAULT_KVM_HOST_SSHD_PORT
export DEFAULT_KVM_PORTS_REDIRECT
export DEFAULT_KVM_DARWIN_CPU
export DEFAULT_IMAGE
export EFAULT_KERNEL_VERSION
export DEFAULT_IMAGE_SOURCE_URL
export INSTALL_ADDITIONAL_DEBS
export ENABLE_REBOOT_AFTER_INSTALLATION
export COPY_IMAGE_BACKUP

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

${SCRIPT_DIR}/start-vm.sh
