#!/bin/bash

: ${RUN_BARE_KERNEL:=1}
: ${VM_HOSTNAME:="hydra-isolated-krun"}
: ${DEFAULT_DIR_IMAGE:="$(pwd)/image-hydra-isolated-krun-bare"}
: ${EXTERNAL_9P_KUBELET_MOUNTS:=1}
: ${DISABLE_9P_KUBELET_MOUNTS:=0}
: ${COPY_IMAGE_BACKUP:=1}
: ${DEFAULT_KVM_DISK_SIZE:=16}
: ${DEFAULT_KVM_HOST_SSHD_PORT:=5557}
: ${DEFAULT_KVM_PORTS_REDIRECT:="30800:8000;30801:8001;30802:8002"}
: ${DEFAULT_KVM_DARWIN_CPU:=4}
: ${DEFAULT_KERNEL_VERSION:=""}
: ${ENABLE_REBOOT_AFTER_INSTALLATION:=0}
: ${COPY_IMAGE_BACKUP:=1}
: ${ENABLE_KRUNKIT:=1}
: ${DEFAULT_RIMD_KERNEL_VERSION:="6.16"}

export RUN_BARE_KERNEL
export VM_HOSTNAME
export DEFAULT_DIR_IMAGE
export EXTERNAL_9P_KUBELET_MOUNTS
export DISABLE_9P_KUBELET_MOUNTS
export COPY_IMAGE_BACKUP
export DEFAULT_KVM_DISK_SIZE
export DEFAULT_KVM_HOST_SSHD_PORT
export DEFAULT_KVM_PORTS_REDIRECT
export DEFAULT_KVM_DARWIN_CPU
export DEFAULT_IMAGE
export EFAULT_KERNEL_VERSION
export DEFAULT_IMAGE_SOURCE_URL
export INSTALL_ADDITIONAL_DEBS
export ENABLE_REBOOT_AFTER_INSTALLATION
export COPY_IMAGE_BACKUP
export ENABLE_KRUNKIT
export DEFAULT_RIMD_KERNEL_VERSION

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

${SCRIPT_DIR}/start-vm.sh
