unset ADDITIONAL_9P_MOUNTS
unset DEFAULT_DIR_IMAGE
unset DISABLE_CONTAINERD_CSI_PROXY
unset DISABLE_9P_KUBELET_MOUNTS
unset DEFAULT_KVM_PORTS_REDIRECT
unset DEBUG DRY_RUN_ONLY
unset ENABLE_VIRTIO_GPU
unset DEFAULT_VIRTIO_GPU_VRAM
unset ALWAYS_REUSE_DISK_IMAGE 

export RUN_BARE_KERNEL=1
export VM_HOSTNAME=hydra-isolated
export DEFAULT_DIR_IMAGE=$(pwd)/image-hydra-isolated-bare
export EXTERNAL_9P_KUBELET_MOUNTS=1
export ADDITIONAL_KERNEL_COMMANDLINE="ENABLE_SSH=true"
export COPY_IMAGE_BACKUP=0
export DEFAULT_KVM_DISK_SIZE=16
export DEFAULT_KVM_HOST_SSHD_PORT=5556
export DEFAULT_KVM_PORTS_REDIRECT="30800:8000;30801:8001;30802:8002"
export DEFAULT_KVM_DARWIN_CPU=4

./start-vm.sh
